
#  PluginManager - Config
#    Note: Be careful while editing the config

# When true, PluginManager may disable itself
selfDestruct: false

# When true, PluginManager will play sound effects
playSound: true